services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    image: employee-app
    container_name: employee_container
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${APP_PORT}:${APP_INTERNAL_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}

      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      APP_HR_PASSWORD: ${APP_HR_PASSWORD}
      LOGIN_FIRST_PASSWORD: ${LOGIN_FIRST_PASSWORD}

volumes:
  mysql_data:
